### ISSUE TITLE
Why are files renamed with _ll_ when published?

### ISSUE THREAD

**Issue by AleksandarDev** [tenacious/Auto.Squirrel#2]
When I create package, all my dll's are renamed.
New files now have this format:
`DeltaCompressionDotNet_ll_.dll`
instead of
`DeltaCompressionDotNet.dll`

Why is this happening? 
With this change, my application won't start properly because of explicit dll bindings in application config file.

This line does that:
https://github.com/tenacious/Auto.Squirrel/blob/master/AutoSquirrel/ShellViewModel.cs#L533

**Comment by tenacious** [comment]
probably it's a typo , i was trying something and i published the files by mistake. 
I think the correct line code is the one below.

**Comment by tenacious** [comment]
try now and close this issue if fixed. Thanks for report

**Comment by AleksandarDev** [comment]
Sorry, I didn't see your notifications. 
As you did exactly the same thing as I did in my source code, it should work just fine. 

I see that you stopped working actively on this project.  Is there an alternative to this, official app or something?
Can I submit some PR's when they're ready?

**Comment by tenacious** [comment]
Auto.Squirrel is 2 days job, since i needed something to automatize
squirrel releases.

I'm using it successfully for my main project .

I don't know if there are alternative out there.

I don't have much experince with github, if i add you as collaborator in
this project , can you upload changes directly ?

​

**Comment by AleksandarDev** [comment]
I'll submit PR's and you can review them and merge. No need to add me to the collaborators list.

We have also successfully used it for 3 projects this week and we like how it simplifies deployment through our non-cloud IIS setup.

Works great for a "2 days job" :D

**Comment by tenacious** [comment]
ok for me ,

2016-05-06 12:54 GMT+02:00 Aleksandar Toplek notifications@github.com:
